name: Run Tests upon PullRequest
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run Test Cases
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Execute test cases
        env:
          ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED: false
        run: ./gradlew test

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ./*/build/reports/tests/
